apiVersion: v1
kind: ConfigMap
metadata:
  name: filament-config
data:
  APP_NAME: "sisinvestfilament"
  APP_ENV: "production"
  APP_DEBUG: "false"
  # ¡Importante! Cambia esto por la IP de tu VPS o tu dominio final antes de subirlo
  APP_URL: "http://investigaciones.mzdevocotal.com"
  ASSET_URL: "http://investigaciones.mzdevocotal.com"
  DB_CONNECTION: "sqlite"
  DB_DATABASE: "/var/www/html/storage/app/db/database.sqlite"
  SESSION_DRIVER: "database"