apiVersion: v1
kind: ConfigMap
metadata:
  name: filament-config
data:
  APP_NAME: "sisinvestfilament"
  APP_ENV: "local"
  APP_DEBUG: "false"
  # ¡Importante! Cambia esto por la IP de tu VPS o tu dominio final antes de subirlo
  APP_URL: "http://144.217.167.89:30080"
  ASSET_URL: "http://144.217.167.89:30080"
  DB_CONNECTION: "sqlite"
  DB_DATABASE: "/var/www/html/storage/app/db/database.sqlite"
  SESSION_DRIVER: "database"