apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filament-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik # Mantenemos esto por compatibilidad
spec:
  ingressClassName: nginx              # <--- ESTO ES LO QUE FALTA
  rules:
    - host: investigaciones.mzdevocotal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filament-app-service
                port:
                  number: 80