apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filament-app-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - investigaciones.mzdevocotal.com
      secretName: filament-tls-secret
  rules:
    - host: investigaciones.mzdevocotal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filament-app-service
                port:
                  number: 80
