apiVersion: v1
kind: Service
metadata:
  name: filament-app-service
  namespace: default
spec:
  type: ClusterIP      # <--- Cambiado a ClusterIP
  selector:
    app: filament-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
                       # <--- La línea de nodePort se elimina por completo